### ISSUE TITLE
python API?

### ISSUE THREAD

**Issue by jgv7** [dguest/pandamonium#5]
Hi Dan,

So I've used this script to do a lot of automation in my production pipeline, however it's a bit hacky as I call a command line argument from within python and then parse your tool's output back into my own python script.

Would it be easy to add a python API for pandamonium so I can get a dictionary of the results directly in my code?

```
from pandamonium import pandamon

results = pandamon( "group.phys-higgs*samplename*.root", user="Jared Vasquez")
do_stuff( results )
```

**Comment by dguest** [comment]
Hey,

The point of the project was to be a lightweight command line tool that follows the unix philosophy, i.e. a few low level tools that communicate through text streams. So I don't think a python api is really within the scope.

Also given that the underlying code is pretty simple and written in python you'd probably get more flexibility and save yourself time in the long run by just copying out the useful bits. I really don't want to be responsible for another HEP disaster of wrapper-on-wrapper obfuscation (I'm looking at you, HistFitter).

But that said, it almost supports what you're asking for as it stands. So you could do 

```python
from pandamon import get_request
req = get_request("group.phys-higgs*samplename*.root", user="Jared Vasquez")
reply_dict = json.loads(urllib2.urlopen(req).read().decode('utf-8'))
```

and you already have the dictionary of results. 

I really advise against this, though, because `get_request` doesn't do enough to merit depending on this project (I encourage you to read it if you don't believe me). It's just a thin wrapper over the bigpanda rest api which you can use directly and is pretty awesome.

If you're going to request a better python api, I'd encourage you to ask the people behind pbook: the stuff I'm doing to get access to `retry` is absolutely disgusting but they could make it a lot cleaner with a few minor changes.

**Comment by jgv7** [comment]
Totally reasonable, thanks for your advice Dan!

**Comment by dguest** [comment]
Cool! I'm going to close this issue, but I'd be interested to see your automated production pipeline. I think having more vocal users for the panda rest api would be a good thing in general: as it stands I think the team probably considers documenting / maintaining it a low priority because most people use the web version.
